---
title: "Playground"
author: "Nicolas Beglinger"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(tmap)
library(SpatialKDE)
tmap_mode("view")
```

```{r}
ch <- read.csv("data/CH.csv",
         sep = "\t",
         header = F,
         col.names = c("geonameid", "name", "asciiname", "alternatenames", "latitude", "longitude", "featureclass", "featurecode", "countrycode", "cc2", "admin1code", "admin2code", "admin3code", "admin4code", "population", "elevation", "dem", "timezone", "modificationdate"))

ch_sf <- ch %>% st_as_sf(
  coords = c("longitude", "latitude"),
  crs = 4326
) %>%
  st_transform(crs = 2056)

```

```{r}
tm_shape(sample_n(filter(ch_sf, elevation > 1000), 6790)) +
  tm_dots(col = "elevation") +
tm_basemap(server = "Stamen.Watercolor")

```

```{r}
hex <- create_grid_hexagonal(
      ch_sf,
      cell_size = 2500,
      side_offset = 0,
      only_inside = FALSE
  )


ch_kde <- kde(
  ch_sf,
  band_width = 50000,
  grid = hex
) %>%
  filter(
    kde_value > 0
  )


tm_tiles("Stamen.Watercolor") +
tm_shape(ch_kde) +
  tm_polygons(
    col = "kde_value",
    alpha = 0.5,
    border.alpha = 0,
    n = 10,
    palette = "viridis"
  )
```





